### ISSUE TITLE
Project Template

### ISSUE THREAD

**Issue by kachergis** [manybabies/manybabies.github.io#11]
For new projects, and to fill out information about existing MB projects. There could even be a submission form for suggested MB projects. What headings do we need? 

* References of target paper(s) for replication (up to 3?)
* Description of phenomenon and why it’s important (250 words?) 
* Proposed leadership team

**Comment by christinabergmann** [comment]
This all sounds good, might be smart to try out a form with current leadership teams.

I might even want to go into more detail:

- Title (e.g. MB1 - Infant-directed speech preference)
- Description of phenomenon (word guide seems reasonable with 250, maybe even shorter)
- Target papers (although I worry that this might create the impression of direct replication)

- Main contact / lead(s)
- Contacts for project management / general questions, method, data analysis (maybe teams can define those categories but it might be good to suggest a more fine-grained division - for MB 1 there were contacts for specific set-ups, questions on ethics, etc).

- OSF page or similar, if applicable (strongly advised to link to some hub)

- Mailing list (to provide a quick signup option)

And to be added later: Preprint, materials, data... 

Does that make sense? I think preprints, materials, and data could be added with news items (if we get this to work...)

**Comment by christinabergmann** [comment]
Any volunteers for taking this on?
