### ISSUE TITLE
Projects: separate sub-pages?

### ISSUE THREAD

**Issue by christinabergmann** [manybabies/manybabies.github.io#18]
To keep things concise and more clearly separate spin-offs from main projects, it might be better to have separate pages for projects (Like on https://manyprimates.github.io/).

**Comment by RodrigoDalBen** [comment]
I believe this was covered on the updated website.

**Comment by christinabergmann** [comment]
Yes, we had the additional idea to define specific responsibilities and/or have a template site, but that needs to be discussed further (I am just mentioning it to not completely forget about it).
