### ISSUE TITLE
MB1-Languages

### ISSUE THREAD

**Issue by melsod** [manybabies/manybabies.github.io#22]
Please update the "MB1: Native Language Comparison" as follows:

Title: MB1: Native Languages Follow-up Study

Topic: How does IDS preference to NA English in MB1 compare to IDS preference measured in non-English speaking babies’ native language?

Leads: Natalia Kartushina & Virginie Durier

Status: Stimulus creation and data collection.

Links: https://osf.io/9j87t/

**Comment by mcfrank** [comment]
done!
