### ISSUE TITLE
Link to propject proposal from "get involved"?

### ISSUE THREAD

**Issue by christinabergmann** [manybabies/manybabies.github.io#53]
Hi, 

I'd suggest adding the project proposal form linked to on the bottom of Projects http://manybabies.stanford.edu/projects/ (or maybe the whole chunk of text?) to this page: http://manybabies.stanford.edu/get_involved/

**Comment by RodDalBen** [comment]
Nice catch! Done: http://manybabies.stanford.edu/get_involved/
